site_name: World Model
theme:
  name: material
  features:
    - toc.integrate        # æŠŠå½“å‰é¡µé¢çš„ TOC é›†æˆåˆ°å·¦ä¾§å¯¼èˆª
    - navigation.expand    # å±•å¼€å½“å‰åˆ†åŒºï¼ˆå¯é€‰ï¼‰
    - navigation.sections  # åˆ†åŒºæ ·å¼ï¼ˆå¯é€‰ï¼‰
    - header.autohide

# è®© Markdown ç”Ÿæˆå¯ç‚¹å‡»çš„é”šç‚¹ï¼Œå¹¶æ§åˆ¶ TOC æ˜¾ç¤ºå±‚çº§
markdown_extensions:
  - toc:
      permalink: true      # æ ‡é¢˜å³ä¾§å‡ºç°ğŸ”—é”šç‚¹
      toc_depth: "2-3"     # åœ¨ä¾§è¾¹æ æ˜¾ç¤º h2~h3ï¼ˆå¯æŒ‰éœ€æ”¹æˆ "2-4"ï¼‰
  - attr_list     # å…è®¸ {...} å±æ€§
  - md_in_html    # å…è®¸åœ¨ Markdown é‡Œå†™å°‘é‡ HTML


nav:
  - home: index.md
  - I Introduction: 01-introduction.md
  - II Preliminaries: 02-preliminaries.md
  - III Overview of the World Model: 03-overview.md
  - IV Functions of the World Model: 04-functions.md
  - V Key Techniques and Notable Challenges: 05-key-tech-challenges.md
  - VI Core Components & Capabilities: 06-core-components.md
  - VII Dataset: 07-dataset.md
  - VIII Conclusion & Future directions: 08-conclusion.md
  - References: 99-references.md
